name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jontze/action-mdbook@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        use-linkcheck: true
        use-mermaid: true
        use-toc: true
        use-opengh: true
    - name: Setup mdbook-katex
      uses: magicgh/mdbook-katex-action@v1
      with:
        version: 'latest'
    - run: |
        cd docs
        mdbook build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/book/html
